---

- debug:
    msg:
      - "Copying Respose file (rsp) for Oracle Client Installation"
      - "URL: {{ rsp_src_path }}"
      - "DST: {{ rsp_win_path }}"

- name: Copy Response file
  win_copy:
    src: "{{ rsp_src_path }}"
    dest: "{{ rsp_win_path }}"
  register: response_file

...