---

- debug:
    msg:
      - "Copying Respose file (rsp) for Oracle Client Installation"

- name: Copy Response file
  win_get_url:
    url: "{{ rsp_src_path }}"
    dest: "{{ rsp_win_path }}"
  register: response_file

...