---

- debug:
    msg:
      - "Copying TNS file into Oracle Client folder"

- name: Copying TNS-file
  win_get_url:
    url: "{{ response_file_path}}{{ tns_file_name }} "
    dest: "{{ hostvars['__DEFAULT_VARS__']['ORACLE_WIN_PATH'] }}\\network\\admin"

...