---

- debug:
    msg:
      - "Copying TNS file into Oracle Client folder"

- name: Copying TNS-file
  win_get_url:
    url: "{{ tns_src_path }}"
    dest: "{{ tns_win_path }}"
  register: tns_file

...