---

# - OCInstallation/DirectoryExist
# - OCInstallation/CopyClient
# - OCInstallation/CopyResponseFile
# - OCInstallation/UnzipOracleClient
# - { role: OCInstallation/UACModifier, uac_input_data: 0 }
- OCInstallation/OCInstall
# - { role: OCInstallation/UACModifier }

- ansible.builtin.include_role:
  name: OCInstallation/DirectoryExist

- ansible.builtin.include_role:
  name: OCInstallation/CopyClient

- ansible.builtin.include_role:
  name: OCInstallation/CopyResponseFile

- ansible.builtin.include_role:
  name: OCInstallation/UnzipOracleClient

- ansible.builtin.include_role:
  name: OCInstallation/UACModifier
  vars:
    - uac_input_data: 0

- debug:
    msg:
      - "Installation of Oracle Client"
      - "Destination: {{ win_unzip.dest }}"
      - "Response file: {{ response_file.dest }}"

- name: Installation of Oracle Client
  ansible.windows.win_package:
    path: '{{ win_unzip.dest }}\client\setup.exe'
    state: present
    arguments: 
      - -waitforcompletion
      - -noconsole
      - -nowait
      - -responseFile
      - "{{ response_file.dest }}" 
      - -silent
      # - -force
  # become: yes
  # become_method: runas
  # vars:
  #   ansible_become_user: "{{ ansible_user }}"
  #   ansible_become_password: {{ ansible_become_password }}

- ansible.builtin.include_role:
  name: OCInstallation/UACModifier
  vars:
    - uac_input_data: 5

...