---

- debug:
    msg:
      - "Installation of Oracle Client"
      - "Destination: {{ win_unzip.dest }}"
      - "Response file: {{ response_file.dest }}"

- name: Installation of Oracle Client
  ansible.windows.win_package:
    path: '{{ win_unzip.dest }}\client\setup.exe'
    state: present
    arguments: 
      - -waitforcompletion
      - -nowait
      - -responseFile
      - "{{ response_file.dest }}" 
      - -silent
      # - -force
  # become: yes
  # become_method: runas
  # vars:
  #   ansible_become_user: "{{ ansible_user }}"
  #   ansible_become_password: {{ ansible_become_password }}

...