---
- name: Install Oracle client onto the Windows Server
  hosts: win2019

  vars:
    download_dir: C:\Users\{{ ansible_user }}\Downloads
    file_name: winx64_12201_client.zip
    respose_file_name: client.rsp
    file_path: 'https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/'
    response_file_path: 'file://\\10.97.142.17\h$\Releases\_Oracle_client_12.2\'

  roles:
    # - { role: CheckData, input_data: 1.5 }
    # - { role: Echo, input_data: "{{ hostvars['__DEFAULT_VARS__']['playbook_dir'] }}" }
    - OCInstallation/OCInstall

...