---
- name: Install Oracle client onto the Windows Server
  hosts: win2019
  vars:
    download_dir: C:\Users\{{ ansible_user }}\Downloads
    msi_url: https://s3.amazonaws.com/aws-cli/AWSCLI32PY3.msi
    file_name: _Oracle_client_12.2
    file_path: 'file://\\10.97.142.17\h$\Releases\'
  tasks:
    - name: Ensure the directory exists
      win_file:
        path: "{{ download_dir }}"
        state: directory
    
    - name: Download binary win_file
      win_get_url:
        url: "{{ msi_url }}"
        dest: "{{ download_dir }}\\awscli.msi"
        use_default_credential: yes
        proxy_use_default_credential: yes
        force: no

    - name: Copy MSC file from network location
      win_get_url:
        url: "{{ file_path }}{{ file_name }}"
        dest: "{{ download_dir }}"
...