---
- name: Install Oracle client onto Windows Server
  hosts: win2019

  roles:
    # - { role: CheckData, input_data: 1.5 }
    # - { role: Echo, input_data: "{{ hostvars['__DEFAULT_VARS__']['playbook_dir'] }}" }
    - OCInstallation/OCInstall

...