---
- name: Install Oracle client onto the Windows Server
  hosts: win2019
  vars:
    download_dir: C:\Users\{{ ansible_user }}\Downloads
#    msi_url: 
  tasks:
    - name: Ensure the directory exists
      win_file:
        path: "{{ download_dir }}"
        state: directory

...