---
- name: Install Oracle client onto the Windows Server
  hosts: win2019
  vars:
    download_dir: C:\Users\{{ ansible_user }}\Downloads
    # msi_url: https://s3.amazonaws.com/aws-cli/AWSCLI32PY3.msi
    file_name: winx64_12201_client.zip
    respose_file_name: client.rsp
    file_path: 'file://\\10.97.142.17\h$\Releases\_Oracle_client_12.2\'
  tasks:
    - name: Ensure the directory exists
      win_file:
        path: "{{ download_dir }}"
        state: directory
    
    # - name: Download binary win_file
    #   win_get_url:
    #     url: "{{ msi_url }}"
    #     dest: "{{ download_dir }}\\awscli.msi"
    #     use_default_credential: yes
    #     proxy_use_default_credential: yes
    #     force: no

    - name: Copying Oracle Client from network location
      win_get_url:
        url: "{{ file_path }}{{ file_name }}"
        dest: "{{ download_dir }}"
      register: win_get_url

    - name: Copy Response file
      win_get_url:
        url: "{{ file_path}}{{ respose_file_name }}"
        dest: "{{ download_dir }}"
      register: response_file

    # - name: Install PSCX
    #   community.windows.win_psmodule:
    #     name: Pscx
    #     state: present

    - name: Unzip oracle client
      community.windows.win_unzip:
        src: "{{ win_get_url.dest }}"
        dest: "{{ download_dir }}"
        # recurse: yes
      register: win_unzip       

    - name: Disable UAC for Administrators
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
        name: ConsentPromptBehaviorAdmin
        data: 0
        type: dword
        state: present

    - name: Installation of Oracle Client
      ansible.windows.win_package:
        path: '{{ win_unzip.dest }}\client\setup.exe -silent -responseFile {{ response_file.dest }}'
        state: present
        # arguments: -silent
      # become: yes
      # become_method: runas
      # vars:
      #   ansible_become_user: "{{ ansible_user }}"
      #   ansible_become_password: {{ ansible_become_password }}

    - name: Enable UAC for Administrators
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
        name: ConsentPromptBehaviorAdmin
        data: 5
        type: dword
        state: present

...