- debug:
    msg:
      - "Change UAC value to '{{ data }}'"

- name: Disable UAC for Administrators
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
    name: ConsentPromptBehaviorAdmin
    data: "{{ uac_input_data }}"
    type: dword
    state: present
