---

- name: "Checking type of input data"
  ansible.builtin.assert:
    # msg:
    #   - "Input_data is not number"
    that:
      - input_data is not number


- debug:
    msg:
      - "Change UAC value to '{{ uac_input_data }}'"

- name: Modification UAC for Administrators
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
    name: ConsentPromptBehaviorAdmin
    data: "{{ uac_input_data }}"
    type: dword
    state: present

...