---

- name: "Checking type of {{ uac_input_data }}"
  ansible.builtin.assert:
    that:
      - uac_input_data is number and uac_input_data is integer
    fail_msg: "Failed!"
    success_msg: "Success!"
    quiet: true

- debug:
    msg:
      - "Change UAC value to '{{ uac_input_data }}'"

- name: Modification UAC for Administrators
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
    name: ConsentPromptBehaviorAdmin
    data: "{{ uac_input_data }}"
    type: dword
    state: present

...