
__EXTERNAL_SETTINGS__:
    hosts:
        __DEFAULT_VARS__:
              TNS_FILE_NAME: "tnsnames.ora"
              RSP_FILE_NAME: "client.rsp"
              ORACLE_WIN_PATH: "C:\\Oracle\\product\\12.2.0\\client_1"
              DISTRIB_PATH: "C:\\distr"
              OC_LOCATION: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/"
              OC_FILE_NAME: "winx64_12201_client.zip"
            #   SRC_PATH: "file://\\10.97.142.17\\h$\\Releases\\_Oracle_client_12.2"
            #   "{{playbook_dir.split('playbooks')[0]}}/Configs_core/Commons/winUtils/"

all:
    children:
        win2019:
            hosts:
                10.97.142.22:
            vars:
                ansible_connection: winrm
                ansible_winrm_transport: credssp
                ansible_winrm_server_cert_validation: ignore

