all:
    children:
        win2019:
            hosts:
                10.97.142.22:
                        ansible_connection: winrm
                        ansible_winrm_transport: credssp
                        ansible_winrm_server_cert_validation: ignore
                        ansible_user: arishmukh1
                        ansible_password: mOafnn
