all:
    children:
        win2019:
            hosts:
                10.97.142.22:
                        ansible_connection: winrm
                        ansible_winrm_transport: credssp
                        ansible_winrm_server_cert_validation: ignore
<<<<<<< HEAD
                        ansible_user: arishmukh1
=======
                        ansible_user: Administrator
>>>>>>> 568a93a6c8a757519995739d977cf64772a8b35c
                        ansible_password: mOafnn
