
__EXTERNAL_SETTINGS__:
    hosts:
        __DEFAULT_VARS__:
              TNS_FILE_NAME: "tnsnames.ora"
              RSP_FILE_NAME: "client.rsp"
              ORACLE_WIN_PATH: "C:\\Oracle\\product\\12.2.0\\client_1"
              DISTRIB_PATH: "C:\\distr"
              OC_LOCATION: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/"
              OC_FILE_NAME: "winx64_12201_client.zip"
              SOFTWARE_TO_INSTALL: 
                VCREDIST_x64_2010: {
                    name: "Redist.x64.2010",
                    file_location: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/",
                    destination_path: "C:\\distr",
                    file_name: "vcredist_x64_2010.exe",
                    product_id: redist.x64.2010,
                    arguments: "/passive",
                }                        

                VCREDIST_x86: {
                    name: "Redist.x86",
                    file_location: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/",
                    destination_path: "C:\\distr",
                    file_name: "vcredist_x86_2017.exe",
                    product_id: redist.x86,
                    arguments: "/S",
                }

                VCREDIST_x64_2017: {
                    name: "Redist.x64.2017",
                    file_location: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/",
                    destination_path: "C:\\distr",
                    file_name: "vcredist_x64_2017.exe",
                    product_id: redist.x64.2017,
                    arguments: "/S",
                }                        

                NET_FRAMEWORK: {
                    name: "Microsoft .NET Framework",
                    file_location: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/",
                    destination_path: "C:\\distr",
                    file_name: "NDP472-KB4054530-x86-x64-AllOS-ENU.exe",
                    product_id: "{BD6F5371-DAC1-30F0-9DDE-CAC6791E28C3}",
                    arguments: "/q /norestart",
                }                        

all:
    children:
        win2019:
            hosts:
                10.97.142.22:
            vars:
                ansible_connection: winrm
                ansible_winrm_transport: credssp
                ansible_winrm_server_cert_validation: ignore
        oel7:
            hosts:
                # 10.97.142.19
                209.97.148.166
            vars:
                ansible_connection: ssh
                ansible_user: root
                # gather_facts: no
                become: yes
                become_method: sudo
s