
__EXTERNAL_SETTINGS__:
    hosts:
        __DEFAULT_VARS__:
              TNS_FILE_NAME: "tnsnames.ora"
              RSP_FILE_NAME: "client.rsp"
              ORACLE_WIN_PATH: "C:\\Oracle\\product\\12.2.0\\client_1"
              DISTRIB_PATH: "C:\\distr"
              OC_LOCATION: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/"
              OC_FILE_NAME: "winx64_12201_client.zip"
              SOFTWARE_TO_INSTALL:
                VCREDIST_2010: {
                    name: "Install redist.x64_2010",
                    file_location: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/",
                    destination_path: "C:\\distr",
                    file_name: "vc_redist_x64_2010.exe",
                    arguments: "/S"                        
                }

                VCREDIST_2017: {
                    name: "Install redist.x64_2017",
                    file_location: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/",
                    destination_path: "C:\\distr",
                    file_name: "vc_redist_x64_2017.exe",
                    arguments: "/S"                        
                }

                NET_FRAMEWORK: {
                    name: "Install Microsoft .NET Framework",
                    file_location: "https://artifactory.mts.ru/artifactory/dev-ocs-generic-local/",
                    destination_path: "C:\\distr",
                    file_name: "ndp472-kb4054530-x86-x64-allos-enu.exe",
                    arguments: "/q /norestart"                        
                }
                     
all:
    children:
        win2019:
            hosts:
                10.97.142.22:
            vars:
                ansible_connection: winrm
                ansible_winrm_transport: credssp
                ansible_winrm_server_cert_validation: ignore

