all:
    children:
        win2019:
            hosts:
                10.97.142.22:
            vars:
                ansible_connection: winrm
                ansible_winrm_transport: credssp
                ansible_winrm_server_cert_validation: ignore

