
__EXTERNAL_SETTINGS__:
    hosts:
        __DEFAULT_VARS__:
              TOPOLOGY: "BARIER_LIMITED"
              TNS_WIN_PATH: "c:\\app\\client\\sa0700moafdeveloper\\product\\12.1.0\\client_1\\network\\admin"
              ORACLE_WIN_PATH: "c:\\app\\client\\sa0700moafdeveloper\\product\\19.0.0\\client_1"
              MSI_REPOSITORY_CONNECTSTRING: "http://x.x.x.x:8081/service/rest/v1/search/assets/download?repository=xxxxx"
              MOAF_REPO: "moaf_Prague"
              OMM_ADRESSES: "x.x.x.x"      #- for ansible-runner-service  ip of OMM (needed for bus.ini.j2 )   
              WORK_DIR: "/home/sa0700moafdeveloper/ansible-runner-service/samples/project"    #for ansible-runner-service path to the group_vars dir 

all:
    children:
        win2019:
            hosts:
                10.97.142.22:
            vars:
                ansible_connection: winrm
                ansible_winrm_transport: credssp
                ansible_winrm_server_cert_validation: ignore

