---

- debug: 
    msg: 
     - "Copying zipped Oracle Client"
     - "src: {{ file_path }}{{ file_name }}"
     - "dst: {{ download_dir }}"

- name: Copying Oracle Client from network location
  win_get_url:
    url: "{{ file_path }}{{ file_name }}"
    dest: "{{ download_dir }}"
  register: win_get_url

...