---

- debug: 
    msg: 
     - "Copying archived Oracle Client"
     - "src: {{ source_file_name }}"
     - "dst: {{ download_dir }}"

- name: Copying Oracle Client
  win_get_url:
    url: "{{ source_file_name }}"
    dest: "{{ download_dir }}"
  register: oracle_client
  when:
    (source_file_name is defined and download_dir is defined)


...