---

# - debug: 
#     msg: 
#      - "Copying archived Oracle Client"
#      - "src: {{ source_file_name }}"
#      - "dst: {{ download_dir }}"

# - name: Copying Oracle Client
#   win_get_url:
#     url: "{{ source_file_name }}"
#     dest: "{{ download_dir }}"
#   register: oracle_client
#   when:
#     (source_file_name is defined and download_dir is defined)

- debug:
    msg: 
      - "Title: {{ item['name'] }}"
      - "File name: {{ item['file_name'] }}"
      - "Arguments: {{ item['arguments'] }}"
  loop: "{{ hostvars['__DEFAULT_VARS__']['SOFTWARE_TO_INSTALL']|value }}"

# - name: Copying additional software
#   win_get_url:
#     url: "{{ source_file_name }}"
#     dest: "{{ download_dir }}"
#   loop: "{{ hostvars['__DEFAULT_VARS__']['SOFTWARE_TO_INSTALL'] }}"

...