---

# - debug: 
#     msg: 
#       - "ssh-copy-id {{ ansible_user }}@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

# - debug:
#     msg:
#       - "{{ hostvars[inventory_hostname] }}"

- name: 'Populate service facts'
  service_facts:

- name: Firewall stopping and disabling
  # vars:
  #   become_method: sudo
  #   # become_user: root
  #   become: yes

  systemd:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: yes

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services["firewalld.service"]

...