---

# - debug: 
#     msg: 
#       - "ssh-copy-id {{ ansible_user }}@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- debug:
    msg:
      - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

# - name: Firewall disabling


...