---

# - debug: 
#     msg: 
#       - "ssh-copy-id {{ ansible_user }}@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- debug:
    msg:
      - "{{ hostvars[inventory_hostname] }}"

# - name: 'Populate service facts'
#   service_facts:

- name: Firewall stopping and disabling
  vars:
    become_method: sudo
    become_user: root
    become: yes

  ansible.builtin.service: 
    name: firewalld
    state: started 
    enabled: no

...