---

# - debug: 
#     msg: 
#       - "ssh-copy-id {{ ansible_user }}@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

# - debug:
#     msg:
#       - "{{ hostvars[inventory_hostname] }}"

- name: 'Populate service facts'
  service_facts:

# - name: Firewall stopping and disabling

#   systemd:
#     name: firewalld
#     state: started
#     enabled: True
#   ignore_errors: yes

- name: Ensure firewalld service is disabled and stopped
  systemd:
    name: firewalld
    state: stopped
    # daemon_reexec: yes
    # daemon_reload: yes
    # scope: global
    enabled: no
    masked: no
  register: firewalld_result
  failed_when: "firewalld_result is failed and 'Could not find the requested service' not in firewalld_result.msg"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '7'

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services["firewalld.service"]

...