---

# - debug: 
#     msg: 
#       - "ssh-copy-id {{ ansible_user }}@{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- debug:
    msg:
      - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: 'Populate service facts'
  service_facts:

- name: Firewall stopping and disabling
  vars:
    become_method: sudo
    become_user: arishmukh1
    become: yes

  ansible.builtin.service: 
    name: "{{ item }}" 
    state: started 
    enabled: no
  # ansible.builtin.command: "{{ item }}"
  loop:
    - firewalld

...