---

- name: "Checking type of {{ input_data }}"
  ansible.builtin.assert:
    that:
      - input_data is number and input_data is integer
    fail_msg:
      - "Input data should be an integer"
    quiet: true

- debug:
    msg:
      - "The next step is available"

...