---

- set_fact: is_checked=False


- name: "Checking type of {{ input_data }}"
  ansible.builtin.assert:
    that:
      - input_data is number and input_data is integer
    fail_msg: "Validation of input data. Failed!"
    success_msg: "Validation of input data. Success!"
    # quiet: true
  ignore_errors: yes

- set_fact: is_checked=True
...