---

- name: "Checking type of {{ input_data }}"
  ansible.builtin.assert:
    that:
      - input_data is number and input_data is integer
    msg: "Validation of {{ input_data }}"
    fail_msg: "Failed!"
    success_msg: "Success!"
    # quiet: true

- debug:
    msg:
      - "The next step is available"

...