---

- set_fact: is_checked=True


- name: "Checking type of {{ input_data }}"
  ansible.builtin.assert:
    that:
      - input_data is number and input_data is integer
    fail_msg: "Validation of input data. Failed!"
    success_msg: "Validation of input data. Success!"
    # quiet: true
  # ignore_errors: yes
  # changed_when: is_checked=False

# - set_fact: is_checked=True
...