---

- debug: 
    msg: 
     - "Checking is directory '{{ hostvars['__DEFAULT_VARS__']['DISTRIB_PATH'] }}' exists"

- name: Ensure the directory exists
  win_file:
    path: "{{ hostvars['__DEFAULT_VARS__']['DISTRIB_PATH'] }}"
    state: directory

...