---

- debug: 
    msg: 
     - "Checking is directory '{{ download_dir }}' exists"

- name: Ensure the directory exists
  win_file:
    path: "{{ hostvars['__DEFAULT_VARS__']['DISTRIB_PATH'] }}"
    state: directory

...